Repository touero/HaVacation, pull requests merged in 2025-03, with the labels that each got.

#3 feat: add github action, issue template and pr template
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/workflows/danger.yml
  .github/workflows/pr_labeler.yml
  Dangerfile
Labels: feature

#7 fix: the attribute UpdateAt not exchangeable
  .github/workflows/validate.yml
  custom_components/__init__.py
  custom_components/ha_vacation/ha_vacation_date.py
  custom_components/ha_vacation/manifest.json
Labels: bug

#9 Auto push releases and fix the attribute not update
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .github/workflows/danger.yml
  .github/workflows/pr_labeler.yml
  .github/workflows/release.yml
  Dangerfile
  README.md
  custom_components/ha_vacation/date_visitor.py
  custom_components/ha_vacation/ha_vacation_date.py
  custom_components/ha_vacation/manifest.json
  custom_components/ha_vacation/sensor.py
  requirements.test.txt
  requirements.txt
Labels: bug, feature

#12 fix: attribute type from boolean to string
  README.md
  custom_components/ha_vacation/constants.py
  custom_components/ha_vacation/ha_vacation_date.py
  custom_components/ha_vacation/manifest.json
  custom_components/ha_vacation/sensor.py
Labels: bug, documentation, feature, question
